export const harryPotterBooks = [
    {
      title: "Harry Potter and the Philosopher's Stone",
      author: "J.K. Rowling",
      yearPublished: 1997,
      bookNumber: 1,
      genre: "Fantasy",
      description: "Harry discovers he is a wizard and begins his magical journey at Hogwarts School of Witchcraft and Wizardry.",
    },
    {
      title: "Harry Potter and the Chamber of Secrets",
      author: "J.K. Rowling",
      yearPublished: 1998,
      bookNumber: 2,
      genre: "Fantasy",
      description: "Harry returns to Hogwarts and uncovers the mystery of the Chamber of Secrets and its terrifying occupant.",
    },
    {
      title: "Harry Potter and the Prisoner of Azkaban",
      author: "J.K. Rowling",
      yearPublished: 1999,
      bookNumber: 3,
      genre: "Fantasy",
      description: "Harry learns about Sirius Black, who has escaped from Azkaban, and uncovers secrets about his parents' past.",
    },
    {
      title: "Harry Potter and the Goblet of Fire",
      author: "J.K. Rowling",
      yearPublished: 2000,
      bookNumber: 4,
      genre: "Fantasy",
      description: "Harry competes in the dangerous Triwizard Tournament and encounters Voldemort's return to power.",
    },
    {
      title: "Harry Potter and the Order of the Phoenix",
      author: "J.K. Rowling",
      yearPublished: 2003,
      bookNumber: 5,
      genre: "Fantasy",
      description: "Harry faces the challenges of the Ministry of Magic's denial of Voldemort's return and leads Dumbledore's Army.",
    },
    {
      title: "Harry Potter and the Half-Blood Prince",
      author: "J.K. Rowling",
      yearPublished: 2005,
      bookNumber: 6,
      genre: "Fantasy",
      description: "Harry discovers Voldemort's past through Dumbledore's lessons and learns about Horcruxes.",
    },
    {
      title: "Harry Potter and the Deathly Hallows",
      author: "J.K. Rowling",
      yearPublished: 2007,
      bookNumber: 7,
      genre: "Fantasy",
      description: "Harry, Ron, and Hermione embark on a mission to destroy Voldemort's Horcruxes and face the final battle.",
    },
  ];
  
  